workflows:
  ios-build:
    name: iOS Unsigned Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app